;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cycle-spacing
        delete-horizontal-space
        kill-region
        kill-visual-line
        mark-sexp
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-shiftmetaleft
        search-forward
        sp-backward-barf-sexp
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        consult-buffer
        describe-key
        end-of-buffer
        ))
